export const galleryMoments = [
  { image: "/brand/campout/first-catch.jpg", label: "Stay patient", title: "Remember the first catch", text: "The reward is bigger when a young person has stayed with the challenge and done the work.", alt: "Smiling Camp Firewalker participants holding a fish they caught" },
  { image: "/brand/campout/trail-team.jpg", label: "Take the trail", title: "Keep moving", text: "A long walk becomes a shared accomplishment when the group moves forward together.", alt: "Camp Firewalker participants hiking together on a wooded trail" },
  { image: "/brand/campout/creek-crossing.jpg", label: "Explore", title: "Find a way through", text: "Creeks and trails invite problem solving, patience, and just enough adventure.", alt: "Camp Firewalker participants exploring a rocky creek" },
  { image: "/brand/campout/camp-kitchen.jpg", label: "Pitch in", title: "Make camp work", text: "Meals, gear, and camp routines give everyone a practical role in the experience.", alt: "Young people and adult leaders preparing food at camp" },
  { image: "/brand/campout/camp-meal.jpg", label: "Gather", title: "Eat well outside", text: "Good food and an open table make room for conversation after a full day outdoors.", alt: "Camp Firewalker participants sharing a meal outdoors" },
  { image: "/brand/campout/shared-table.jpg", label: "Share the table", title: "Make room for everyone", text: "Some of the most lasting moments happen when the whole group slows down together.", alt: "Camp Firewalker participants and volunteers gathered around a meal" },
  { image: "/brand/campout/range-day.jpg", label: "Learn safely", title: "Focus at the range", text: "Clear instruction and close supervision help a new skill become real confidence.", alt: "A young Camp Firewalker participant receiving supervised BB gun instruction" },
  { image: "/brand/campout/trail-leader.jpg", label: "Trusted guidance", title: "Someone shows up", text: "Steady adult leaders make room for young people to try, learn, and own the experience for themselves.", alt: "A smiling Camp Firewalker adult leader at a wooded campsite" },
  { image: "/brand/campout/tent-morning.jpg", label: "Wake up outside", title: "Start somewhere new", text: "A morning at camp opens another day to try, learn, and belong.", alt: "A Camp Firewalker participant outside a tent in the morning" },
  { image: "/brand/campout/creek-friends.jpg", label: "Explore together", title: "Follow curiosity", text: "The landscape becomes a place to notice more, ask questions, and share discoveries.", alt: "Camp Firewalker participants exploring beside a creek" },
  { image: "/brand/campout/campfire-circle.jpg", label: "Come together", title: "End the day around the fire", text: "Stories and reflection feel different with a campfire at the center of the circle.", alt: "Camp Firewalker group gathered around a campfire" },
  { image: "/brand/campout/campfire-group.jpg", label: "Carry it home", title: "A story worth keeping", text: "The campout ends, but the confidence, friendships, and memories travel home.", alt: "Camp Firewalker participants enjoying an evening campfire" },
];
