export const galleryMoments = [
  { image: "/brand/experiences/lake-cleanup.jpg", label: "Take responsibility", title: "Leave it better", text: "A shared adventure starts with caring for the place that makes it possible.", alt: "Young people and adult volunteers cleaning a lakeshore together" },
  { image: "/brand/gallery/album-01.jpg", label: "Carry your share", title: "Finish the job", text: "Everyone contributes. Even the work becomes part of the story they take home.", alt: "Young people carrying collected litter away from a Texas lakeshore" },
  { image: "/brand/gallery/album-02.jpg", label: "Stay curious", title: "Look closely", text: "The outdoors invites questions, attention, and the thrill of discovering something real.", alt: "A young participant looking at fish with an adult volunteer beside the lake" },
  { image: "/brand/gallery/album-03.jpg", label: "Learn together", title: "Gather around", text: "The lesson lands differently when everyone can see it, ask about it, and try it themselves.", alt: "Young participants gathering with volunteers for a lakeside fishing lesson" },
  { image: "/brand/gallery/album-04.jpg", label: "Find your place", title: "Room to breathe", text: "Open water, a long dock, and enough space for every young person to settle into the day.", alt: "Young people and volunteers spread across a fishing dock on a Texas lake" },
  { image: "/brand/gallery/album-06.jpg", label: "Build a skill", title: "Someone beside you", text: "A patient adult, a fishing rod, and one small step toward doing it independently.", alt: "An adult volunteer helping a young participant prepare a fishing rod on a dock" },
  { image: "/brand/gallery/album-08.jpg", label: "Make a choice", title: "Pick your spot", text: "The experience becomes theirs when they begin making decisions and trusting their own instincts.", alt: "A young participant pointing across the lake while holding a fishing rod" },
  { image: "/brand/gallery/album-09.jpg", label: "Practice patience", title: "Stay with it", text: "Not every meaningful moment is loud. Sometimes growth looks like waiting and paying attention.", alt: "A young participant watching a fishing line from the edge of a dock" },
  { image: "/brand/gallery/album-10.jpg", label: "Own the moment", title: "Quiet focus", text: "By the end of the day, the rod is in his hands and the next move is his to make.", alt: "A young participant holding a fishing rod independently on a lakeside dock" },
];
